### ISSUE TITLE
Offhand Shulkers delete picked up modded items

### ISSUE THREAD

**Issue by BoshaNova** [FamroFexl/ShulkerLoader#2]
Shulker box doesn't pick up anything under a modded id name.

**Mod Ver**
Shulker loader ver 1.0.6

**Loader Ver**
Fabric API 0.69.0+1.19.2
Fabric Loader 0.14.11

**Mods Used**
Create
Fabric API
Fabric Language Kotlin
Shulker Loader

**Minecraft Ver**
Minecraft ver 1.19.2

**To repoduce**
Collect Items

**Comment by FamroFexl** [comment]
Unfortunately, this is a feature of Shulker Loader that was added but never tested. I will make sure this works in the next release.
