### ISSUE TITLE
mod list for my 1.17.1 crash if that helps

### ISSUE THREAD

**Issue by RYUKxAnime** [FamroFexl/ShulkerLoader#4]
[18:23:52] [main/INFO]: Loading 344 mods:
	- accurateblockplacement 1.0.10
	- additionaladditions 2.2.0
	   \-- libgui 4.2.1+1.17.1
	        |-- jankson 3.0.1+j1.2.0
	        \-- libninepatch 1.1.0
	- advancementinfo 1.17.1-fabric0.36.1-1.3
	- advdebug 2.3.0
	- airtide 1.0.0
	- always-drop-loot 5.1.0+mc1.17.1
	- animal_feeding_trough 1.0.2
	- animatica 0.4+1.17
	- appleskin 2.4.0+mc1.17.1
	- architectury 2.10.12
	- armorhotswap 1.7
	- assembly 21w06a-1.0.0
	- autoafkfisher 1.0.1+build.4
	- axesareweapons 1.6.0
	- axolotlitemfix 1.1.2
	- balm-fabric 1.9.0+0
	- beaconoverhaul 1.4.3+1.17
	   |-- com_electronwill_night-config_core 3.6.5
	   |-- com_electronwill_night-config_toml 3.6.5
	   |-- fabric-api-base 0.4.0+cf39a74318
	   |-- fabric-resource-loader-v0 0.4.10+f09604ce18
	   |-- fabric-tag-extensions-v0 1.2.3+cf39a74318
	   \-- reach-entity-attributes 2.1.1
	- beaconsforall 2.0.1-1.17.1
	- bedrockminer 1.0.0
	- bedspreads 1.4.0-1.17
	- betterbeacon 1.0.5
	- betterbeds 1.2.0
	- betterbiomeblend 1.17.0-1.2.9-fabric
	- betterf3 2.0.0
	- bettermounthud 1.1.2
	- betterrecipebook 1.5.5
	- bfapi 1.1.11
	   \-- packet_tweaker 0.2.0+1.17.1
	- blastproof_netherite 2.0.0+mc1.17
	- boat_step_up 1.2.1
	- boatbreakfix 1.0.11
	- boatcontainer 1.2.3
	- boatiview 0.0.2
	- borderlessmining 1.1.1+1.17
	- breakfree 1.0.0
	- cameraoverhaul 1.4.0-fabric-universal
	- capturetomob 1.0.2
	- carpet 1.4.57
	- cem 0.7.1_S7_1.17
	   \-- completeconfig 1.0.0
	- charmonium 3.3.0
	   \-- com_moandjiezana_toml_toml4j 0.7.2
	- cherishedworlds 2.0.1-1.17.1
	- chesttracker 1.1.1
	   \-- whereisit 1.14.3
	- citresewn 0.9.1+1.17.1
	- cleancut 1.17-4.0-fabric
	- clickthrough 1.17.1-fabric0.36.1-0.4
	   |-- crowdin-translate 1.3+1.17
	   \-- gbfabrictools 1.3.4+1.17
	- clienttweaks 6.0.0+0
	- cloth-api 2.1.62
	   |-- cloth-client-events-v0 2.1.62
	   |-- cloth-common-events-v1 2.1.62
	   |-- cloth-datagen-api-v1 2.1.62
	   |-- cloth-scissors-api-v1 2.1.62
	   \-- cloth-utils-v1 2.1.62
	- cloth-config2 5.3.63
	   \-- cloth-basic-math 0.6.1
	- cmdkeybind 1.5.2-1.17
	   \-- kyrptconfig 1.1.10-1.17
	        \-- blue_endless_jankson 1.2.1
	- collective-fabric 4.26
	   \-- fiber 0.23.0-2
	- colorfulsubtitles 1.0.0
	- colormatic 2.3.1+mc.1.17.1
	- colytra 2.0.0-1.17
	   \-- caelus 0.0.16-1.17
	- comforts 0.0.7-1.17.1
	   |-- cardinal-components-base 3.1.1
	   |-- cardinal-components-entity 3.1.1
	   \-- somnus 0.0.13-1.17.1
	- command-gui-buttons 1.2.0
	   |-- com_alibaba_fastjson 1.2.56
	   |-- com_cedarsoftware_json-io 4.10.1
	   \-- com_googlecode_json-simple_json-simple 1.1.1
	- connectiblechains 1.2.3
	- continuity 1.1.0+1.17
	- coordinatesdisplay 2.0.0mc1.17.1
	   |-- cotton-config 1.0.0-rc.7
	   \-- cotton-logging 1.0.0-rc.4
	- copbea 1.0.1
	- couplings 1.6.0+1.17
	   \-- fabric-networking-api-v1 1.0.14+5847535018
	- craftingpad 1.17.1-fabric0.36.1-1.0.5
	   \-- crowdin-translate 1.3+1.17
	- craftobsidian 1.17.1
	- crawl 0.9.3
	   \-- mm 2.3
	- cullleaves 2.3.1
	- cyclepaintings-fabric 2.1
	- dark-loading-screen 1.6.11
	- dashloader 3.1.1+1.17
	   |-- com_github_luben_zstd-jni 1.5.2-2
	   |-- dev_quantumfusion_dashloader_dashloader-core 1.4.0
	   \-- dev_quantumfusion_hyphen 0.2.0
	- day_dream 1.0.3
	- deepslatecutting 1.2.2
	   \-- maybe-more-data 1.0.0-1.17.1
	- despawningeggshatch-fabric 2.3
	- detailab 2.6.1+1.17.1-fabric
	- diggusmaximus 1.5.1-1.17
	   \-- kyrptconfig 1.1.10-1.17
	        \-- blue_endless_jankson 1.2.1
	- doublejump 1.0.1+mc1.17
	- durabilityviewer 1.17.1-fabric0.36.1-1.10.2
	   |-- crowdin-translate 1.3+1.17
	   \-- gbfabrictools 1.3.4+1.17
	- easyautocrafting 1.2+1.17
	- easybreeding 7.0.0
	- easyelytratakeoff-fabric 2.2
	- easymagic 2.0.2
	- eatinganimationid 1.2
	- editsign 2.2.4
	- enchantingchanges 1.0.4
	- enchantinginfuser 2.0.0
	- enchantmentdescriptions 4.0.3
	- enhanced_attack_indicator 1.0.2+1.17
	- enhancedblockentities 0.5+1.17
	- entityculling 1.5.0
	- expanded_trident_enchanting 1.0.2
	- explorerscompass 1.17.1-2.0.2-fabric
	- extendedbonemeal-fabric 1.6
	- extrasounds 2.2.0+1.17
	   |-- advanced_runtime_resource_pack 0.5.1
	   \-- soundcategories 1.2.0+1.17
	- extremesoundmuffler 3.22_fabric-1.17.1
	   \-- fiber 0.23.0-2
	- fabric 0.46.1+1.17
	   |-- fabric-api-lookup-api-v1 1.5.0+e821752d18
	   |-- fabric-biome-api-v1 3.2.2+cf39a74318
	   |-- fabric-blockrenderlayer-v1 1.1.6+cf39a74318
	   |-- fabric-command-api-v1 1.1.4+cf39a74318
	   |-- fabric-commands-v0 0.2.3+cf39a74318
	   |-- fabric-containers-v0 0.1.13+cf39a74318
	   |-- fabric-content-registries-v0 0.4.1+3447790d18
	   |-- fabric-crash-report-info-v1 0.1.6+cf39a74318
	   |-- fabric-dimensions-v1 2.0.15+b556f28c18
	   |-- fabric-entity-events-v1 1.4.1+377137cc18
	   |-- fabric-events-interaction-v0 0.4.12+e99fbe1218
	   |-- fabric-events-lifecycle-v0 0.2.4+cf39a74318
	   |-- fabric-game-rule-api-v1 1.0.8+cf39a74318
	   |-- fabric-item-api-v1 1.3.0+6617390918
	   |-- fabric-item-groups-v0 0.3.2+cf39a74318
	   |-- fabric-key-binding-api-v1 1.0.6+2a2bb57318
	   |-- fabric-keybindings-v0 0.2.4+cf39a74318
	   |-- fabric-lifecycle-events-v1 1.4.6+0392f3a618
	   |-- fabric-loot-tables-v1 1.0.5+cf39a74318
	   |-- fabric-mining-level-api-v1 1.0.3+cf39a74318
	   |-- fabric-mining-levels-v0 0.1.7+cf39a74318
	   |-- fabric-models-v0 0.3.1+cf39a74318
	   |-- fabric-networking-blockentity-v0 0.2.12+cf39a74318
	   |-- fabric-networking-v0 0.3.3+cf39a74318
	   |-- fabric-object-builder-api-v1 1.11.1+f907116918
	   |-- fabric-object-builders-v0 0.7.8+cf39a74318
	   |-- fabric-particles-v1 0.2.5+cf39a74318
	   |-- fabric-registry-sync-v0 0.8.0+ea29b33318
	   |-- fabric-renderer-api-v1 0.4.6+ce16ae5918
	   |-- fabric-renderer-indigo 0.4.10+ce16ae5918
	   |-- fabric-renderer-registries-v1 3.2.6+cf39a74318
	   |-- fabric-rendering-data-attachment-v1 0.1.6+cf39a74318
	   |-- fabric-rendering-fluids-v1 0.2.1+cf39a74318
	   |-- fabric-rendering-v0 1.1.7+cf39a74318
	   |-- fabric-rendering-v1 1.10.1+377137cc18
	   |-- fabric-resource-conditions-api-v1 1.0.1+591a0f2118
	   |-- fabric-screen-api-v1 1.0.5+cf39a74318
	   |-- fabric-screen-handler-api-v1 1.1.9+cf39a74318
	   |-- fabric-structure-api-v1 1.2.0+48a9ad8918
	   |-- fabric-textures-v0 1.0.7+cf39a74318
	   |-- fabric-tool-attribute-api-v1 1.3.3+3b96517518
	   \-- fabric-transfer-api-v1 1.5.4+cf39a74318
	- fabric-language-kotlin 1.8.7+kotlin.1.7.22
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.7.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.7.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.22
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.18.5
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1
	- fabricloader 0.14.17
	- fastchest 1.2+1.17
	- fasterminecarts 2.2.0
	- fastfurnace 1.17-3.0
	- fastopenlinksandfolders 1.1.1
	- fatxporbs 1.0.1
	- firstperson 2.1.0
	- fishonaleash 1.17.1-1.0.0
	- fixedglowsquids 1.2
	- flighthelper 1.17.1-fabric0.36.1-1.2.2
	   \-- gbfabrictools 1.3.4+1.17
	- flycommand 1.17.1-1.2
	- flytre_lib 1.4.3
	   |-- flytre-lib-base 1.3.0
	   |-- flytre-lib-compat 1.0.0
	   |-- flytre-lib-config 1.1.0
	   |-- flytre-lib-event 1.0.1
	   |-- flytre-lib-gui 1.0.0
	   \-- flytre-lib-storage 2.3.2
	- forgeconfigapiport 2.0.2
	- forgottengraves v1.2.1-mc1.17.1
	- fullscreeno 1.0.0
	- goblintraders 1.4.1
	   \-- thonkutil 1.3
	- goldenhoppers 1.3.0
	- grindenchantments 1.6.4+1.18.2
	- held-item-info 1.4.2+1.18
	- highlighter 1.1.2
	- horsebuff 2.0.1
	- horsestatsvanilla 4.1.8
	- hydrogen 0.3
	- iceberg 1.0.27
	- iknowwhatimdoing 4.1.1
	- indium 1.0.1+mc1.17.1
	- infinitemusic 1.3.0
	- infinitetrading-fabric 2.1
	- infinity-on-trident 2.0.1
	- infinityfix 1.1.0
	- inventory_control_tweaks 1.3.9+MC1.17-1.17.1
	   \-- crowdin-translate 1.3+1.17
	- inventoryhotswap 1.3.0
	- inventoryhud 3.4.1
	- inventoryprofilesnext 1.8.6
	- inventorytotem-fabric 1.5
	- invmove 1.17-0.1.1
	- iris 1.2.4-build.37
	   |-- fabric-command-api-v1 1.1.4+cf39a74318
	   |-- fabric-key-binding-api-v1 1.0.6+2a2bb57318
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_slf4j_slf4j-api 1.7.12
	- iseelava 1.0.0
	- itemmodelfix 1.0.3+1.17
	- itemscroller craftfix-1.2.6
	- java 17
	- keep_someinventory_mr 1-v1.2.0
	- keepthatmusic 0.0.3
	- keybindsgalore 1.0
	- kleeslabs 10.0.0+0
	- languagereload 1.2
	- libipn 1.0.8
	- libraryferret 2.0.0
	- litematica 0.9.0
	- lithium 0.7.5
	- magiclib 0.6.212+a47eb26-stable
	   \-- magiclib-1_17_1 0.6.212+a47eb26-stable
	- malilib 0.10.0-dev.26
	- masa_gadget_mod 3.0.0
	   \-- masa_gadget_mod-1_17_1 3.0.0
	- mcpitanlibarch 1.4.9-1.17-fabric
	- minecraft 1.17.1
	- minihud 0.20.0
	- mob_catcher 1.0.12
	- mobhealthbar 1-17-1-fabric
	- mobspawninglightlevel 1.2.0
	- modmenu 2.0.17
	- monsters_in_the_closet 1.0.2+1.17
	- mousewheelie 1.8.8+mc1.17.1
	   |-- amecsapi 1.3.5+mc1.17.1
	   |-- coat 1.0.0-beta.17+mc1.17
	   |-- fabric-events-interaction-v0 0.4.12+e99fbe1218
	   |-- fabric-item-api-v1 1.3.0+6617390918
	   |-- fabric-key-binding-api-v1 1.0.6+2a2bb57318
	   |-- fabric-lifecycle-events-v1 1.4.6+0392f3a618
	   |-- fabric-tool-attribute-api-v1 1.3.3+3b96517518
	   |-- tweed4_annotated 1.3.0+mc1.17
	   |-- tweed4_base 1.5.0+mc1.17
	   |-- tweed4_data 1.2.1
	   |-- tweed4_data_hjson 1.1.0
	   |-- tweed4_tailor_coat 1.1.2+mc1.17
	   \-- tweed4_tailor_screen 1.1.1+mc1.17
	- nametagtweaks-fabric 1.7
	- naturescompass 1.17.1-2.0.1-fabric
	- no_fog 1.3.2+1.16.5-1.19.3
	- no_nether_portal_overlay 1.0.1
	- no_teleport_cooldown 1.0.2
	- noexpensive 1.17-Fabric-1.3.0
	- nofade 1.17-2.0.0
	- nostrip 1.2.2-1.17+
	- notenoughcrashes 4.1.4+1.17.1
	- overflowtosaturation 1.0.0
	- packed-inventory 0.2.2+1.17.1
	   |-- fabric-key-binding-api-v1 1.0.6+2a2bb57318
	   |-- fabric-lifecycle-events-v1 1.4.6+0392f3a618
	   \-- fabric-rendering-v1 1.10.1+377137cc18
	- paintings 1.17.1-1.0.0.3
	- particlerain 1.5.0
	- passiveshield-fabric 2.0
	- perfectaccuracy 1.2
	- pickablevillagers 1.1.4+1.17.1
	- presencefootsteps r35-1.17
	   \-- kirin 1.9.2-beta.1
	- puddles 1.2.0
	   \-- midnightlib 0.2.9
	- puzzleslib 2.0.3
	- reeses-sodium-options 1.4.9+mc1.17.1-build.65
	- replaymod 1.17.1-2.6.10
	- right-click-harvest 1.1.0
	- rocks 1.5.1
	- roughlyenoughitems 6.5.433
	- roughlyenoughresources 2.2.0
	- ruined_equipment 2.0.0
	- scaffoldingdropsnearby-fabric 1.5
	- screenshotclipboard 1.0.8
	- shulkerpick 1.0.0-1.17
	- sihywtcamc 1.4.1+1.17.1
	   \-- reach-entity-attributes 2.1.1
	- silence 1.17.1-fabric0.36.1-1.0.1
	   |-- crowdin-translate 1.3+1.17
	   \-- gbfabrictools 1.3.4+1.17
	- silkthatamethyst 1.0.0
	- silktouch_spawners 0.0.1
	- simplehomes 1.0.0
	- sleepsooner-fabric 2.6
	- slight-gui-modifications 2.0.3
	   |-- org_codehaus_groovy_groovy 3.0.8
	   \-- org_codehaus_groovy_groovy-jsr223 3.0.8
	- smoothboot 1.16.5-1.6.0
	- sodium 0.3.4+build.13
	   \-- org_joml_joml 1.10.2
	- sodium-extra 0.4.5+mc1.17.1-build.41
	   |-- caffeineconfig 1.1.0
	   \-- fabric-lifecycle-events-v1 1.4.6+0392f3a618
	- sound_physics_remastered 1.17.1-1.0.6
	- speedtrading 2.1.0+1.17
	- stackrefill-fabric 2.1
	- starlight 1.0.0+fabric.73f6d37
	- statuseffecttimer 1.1.1+1.17.1
	- stepup 1.17.1-fabric0.36.1-1.1
	   |-- crowdin-translate 1.3+1.17
	   \-- gbfabrictools 1.3.4+1.17
	- storagerecursion 1.0.0
	- taxfreelevels 1.2
	- thymine 1.8.0
	- timechanger 1.1.0
	- tntbreaksbedrock-fabric 1.8
	- tradingpost 2.0.0
	- trampledisablerfabric 1.0.3
	- trashslot 10.0.0+0
	- treeharvester-fabric 5.1
	- tweakeroo 0.11.0
	- uncraftingtable76 1.1.7
	- upgradedshulkers 1.1.1-1.17
	   \-- shulkerutils 1.0.4-1.17
	- villagerdeathmessages-fabric 2.2
	- villagerhelper 2.0.0
	- villagernames 2.0.1
	- villagers-follow-emeralds 1.1.0
	- visuality 0.3.4
	   \-- goosik-config 0.2.0
	- waterdripsound 1.17-0.3.0
	- wi_zoom 1.3-MC1.17.1
	- worldtime 1.17.1-fabric0.36.1-1.3.1
	   |-- crowdin-translate 1.3+1.17
	   \-- gbfabrictools 1.3.4+1.17
	- wthit 3.11.2
	- wthit-plugins 1.0.6+1.18.2
	- xaerominimap 22.16.3
	- xaeroworldmap 1.28.7

**Comment by FamroFexl** [comment]
Please post in the same issue next time, thanks.
