### ISSUE TITLE
Add compatibility with Carpet-AMS-Addition

### ISSUE THREAD

**Issue by sternschnaube** [FamroFexl/ShulkerLoader#5]
### Suggestion

https://github.com/Minecraft-AMS/Carpet-AMS-Addition/blob/master/README_en.md

The mod offers a rule to double the Shulker Box inventory size, but the Shulker Box on the second hand doesn't put the items into the new slots.

Compatibility would be great 😊

**Comment by FamroFexl** [comment]
I'll see what I can do.

**Comment by venaminecraft** [comment]
Thanks 😄

**Comment by venaminecraft** [comment]
Any update on this @FamroFexl?

**Comment by FamroFexl** [comment]
Implemented

**Comment by venaminecraft** [comment]
Thank you, awesome!! 😊
